version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #restart: unless-stopped
    env_file: docker.env
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./diarios:/usr/src/app/diarios
      - /etc/localtime:/etc/localtime:ro
  web:
    image: httpd:alpine
    restart: unless-stopped
    ports:
      - "8095:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5m
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./public:/usr/local/apache2/htdocs/
